name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install requests

    - name: Get latest release
      id: latest_release
      run: |
        python - <<EOF
        import requests

        def get_latest_release(repo):
            url = f"https://api.github.com/repos/{repo}/releases/latest"
            response = requests.get(url)
            
            if response.status_code == 200:
                release_info = response.json()
                tag_name = release_info["tag_name"]
                release_notes = release_info["body"]
                print(tag_name)
                print(release_notes)
            
        get_latest_release("Ehviewer-Overhauled/Ehviewer")
        EOF

    - name: Update README
      run: |
        python - <<EOF
        def update_readme(latest_release, release_notes):
            readme_content = f"Latest Release: {latest_release}\n\nRelease Notes:\n{release_notes}"
            with open("README.md", "w") as file:
                file.write(readme_content)
        
        latest_release = "${{ steps.latest_release.outputs.stdout }}"
        release_notes = "${{ steps.latest_release.outputs.stderr }}"
        update_readme(latest_release, release_notes)
        EOF

    - name: Upload README artifact
      uses: actions/upload-artifact@v2
      with:
        name: updated-readme
        path: README.md
