name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install requests

    - name: Get latest release
      id: latest_release
      run: |
        python - <<EOF
        import requests

        def get_latest_release(repo):
            url = f"https://api.github.com/repos/{repo}/releases/latest"
            response = requests.get(url)
            
            if response.status_code == 200:
                release_info = response.json()
                tag_name = release_info["tag_name"]
                release_notes = release_info["body"]
                print(tag_name)
                print(release_notes)
            
        get_latest_release("Ehviewer-Overhauled/Ehviewer")
        EOF

    - name: Update README
      run: |
        python - <<EOF
        def update_readme(latest_release, release_notes):
            readme_template_file = "README_TEMPLATE.md"  # 替换为包含占位符的 README 模板文件路径
            readme_output_file = "README.md"  # 替换为生成的 README 文件路径
            
            with open(readme_template_file, "r") as template_file:
                template_content = template_file.read()
            
            # 更新版本号和更新内容
            new_content = template_content.replace("{{latest_release}}", latest_release)
            new_content = new_content.replace("{{release_notes}}", release_notes)
            
            with open(readme_output_file, "w") as output_file:
                output_file.write(new_content)
        
        latest_release = "${{ steps.latest_release.outputs.stdout }}"
        release_notes = "${{ steps.latest_release.outputs.stderr }}"
        update_readme(latest_release, release_notes)
        EOF

    - name: Upload README artifact
      uses: actions/upload-artifact@v2
      with:
        name: updated-readme
        path: README.md
